import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as ddb from 'aws-cdk-lib/aws-dynamodb';
import * as fs from 'fs';
import * as path from 'path';
// scanner-actions.json is GENERATED by `cmd/gen-policy` (`make generate-policy`)
// from the single source-of-truth Go literal list. It is the ONLY place the
// scanner IAM action surface is defined; CI (`make check-policy`) fails on drift.
// resolveJsonModule is enabled in tsconfig.json.
import * as scannerPolicy from '../policy/scanner-actions.json';

export interface SecurityStackProps extends cdk.StackProps {
  readonly resultsBucket: s3.IBucket;
  readonly scansTable: ddb.ITable;
  readonly orgScanning: boolean;
  /**
   * Root OU id to target with the SERVICE_MANAGED StackSet (your org root,
   * e.g. r-exam). Used as the deployment target for the member-account scanner role.
   */
  readonly orgRootId?: string;
  /** ExternalId the orchestrator must pass on sts:AssumeRole (confused-deputy guard). */
  readonly scannerExternalId?: string;
  /**
   * AWS Organizations id used to gate the member scanner-role trust policy
   * (aws:PrincipalOrgID). Your org id, e.g. o-exampleorgid.
   */
  readonly organizationId?: string;
  /**
   * How CloudFormation creates the SERVICE_MANAGED scanner-role StackSet:
   *  - 'DELEGATED_ADMIN' (default): deploy from the Audit account, which must be
   *    registered as a StackSets delegated administrator in the management account.
   *    This is the recommended Audit-account model (least standing access to the
   *    management/payer account).
   *  - 'SELF': deploy directly from the management account (only valid when this
   *    stack is itself deployed from the management account).
   * Allowed values mirror CloudFormation's AWS::CloudFormation::StackSet CallAs
   * (SELF | DELEGATED_ADMIN), which applies only to the SERVICE_MANAGED model.
   */
  readonly stackSetCallAs?: 'DELEGATED_ADMIN' | 'SELF';
}

export class SecurityStack extends cdk.Stack {
  /** Name of the member-account scanner role (matches the StackSet template). */
  public readonly scannerRoleName: string;
  /** ARN of the orchestrator role in this (Audit) account — only when orgScanning. */
  public readonly orchestratorRoleArn?: string;
  /**
   * The orchestrator role itself, when orgScanning. The Scanner Lambda uses THIS
   * as its execution role so the principal that calls sts:AssumeRole matches the
   * member/mgmt scanner-role trust policies (which trust the orchestrator).
   */
  public readonly orchestratorRole?: iam.Role;

  /**
   * The custom least-privilege READ policy, created lazily and shared by every
   * scanner role in this stack (orchestrator + local management-account role).
   * Its action list is the generated source of truth (scanner-actions.json).
   */
  private scannerReadPolicy?: iam.ManagedPolicy;

  constructor(scope: Construct, id: string, props: SecurityStackProps) {
    super(scope, id, props);

    this.scannerRoleName = 'CryptaMapScannerRole';
    const externalId = props.scannerExternalId ?? 'cryptamap-scanner';
    const organizationId = props.organizationId ?? 'o-exampleorgid';
    // Default to the Audit-account model: deploy the SERVICE_MANAGED StackSet as a
    // delegated administrator (the Audit account must be registered as a StackSets
    // delegated admin in the management account — see docs). SELF is opt-in only,
    // for the case where this stack is deployed directly from the management account.
    const stackSetCallAs = props.stackSetCallAs ?? 'DELEGATED_ADMIN';

    if (props.orgScanning) {
      const orgRootId = props.orgRootId ?? 'r-exam';

      // ------------------------------------------------------------------
      // 1) Orchestrator role (lives in the Audit / delegated-admin account).
      //    The Step Functions state machine + scanner Lambda use this to
      //    assume CryptaMapScannerRole in each member account. sts:AssumeRole
      //    lives HERE only — never on the member scanner role.
      // ------------------------------------------------------------------
      const orchestrator = new iam.Role(this, 'OrchestratorRole', {
        roleName: 'CryptaMapOrchestratorRole',
        assumedBy: new iam.CompositePrincipal(
          new iam.ServicePrincipal('lambda.amazonaws.com'),
          new iam.ServicePrincipal('states.amazonaws.com'),
        ),
        description:
          'CryptaMap orchestrator - the scanner Lambda execution role; assumes CryptaMapScannerRole in each account.',
        managedPolicies: [
          // Lambda execution basics (CloudWatch Logs) only. The crypto-scan READ
          // surface is NO LONGER the broad AWS-managed ReadOnlyAccess: it is the
          // custom least-privilege list generated from cmd/gen-policy (added below
          // via addScannerReadPolicy), so the orchestrator's permissions can never
          // silently drift from the scanner code.
          iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
        ],
      });
      // Custom least-privilege READ surface (the same source-of-truth action list
      // the member scanner role gets). The scanner Lambda RUNS AS this role for the
      // local/management-account branch of the fan-out, so it needs the reads too.
      this.addScannerReadPolicy(orchestrator);
      orchestrator.addToPolicy(new iam.PolicyStatement({
        sid: 'AssumeMemberScannerRole',
        effect: iam.Effect.ALLOW,
        actions: ['sts:AssumeRole'],
        resources: [`arn:${cdk.Aws.PARTITION}:iam::*:role/${this.scannerRoleName}`],
      }));
      // The EXACTLY THREE resource-scoped WRITES (from scanner-actions.json,
      // generated). These live on the ORCHESTRATOR ONLY — never on a member
      // scanner role — and are scoped to this account's results bucket, scans
      // table, and Security Hub product ARN.
      this.addOrchestratorWrites(orchestrator, props);
      this.orchestratorRole = orchestrator;
      // The orchestrator needs to enumerate accounts in the org. With the Audit
      // account as delegated admin for Organizations, ListAccounts is permitted
      // from here; on the management account this same action also works.
      orchestrator.addToPolicy(new iam.PolicyStatement({
        sid: 'ListOrgAccounts',
        effect: iam.Effect.ALLOW,
        actions: ['organizations:ListAccounts'],
        resources: ['*'],
      }));
      this.orchestratorRoleArn = orchestrator.roleArn;

      // ------------------------------------------------------------------
      // 1b) Local scanner role in THIS (management/orchestrator) account.
      //     The SERVICE_MANAGED StackSet (below) only deploys CryptaMapScannerRole
      //     to MEMBER accounts — never to the management account itself. Without
      //     this, the org fan-out's branch for the management account fails to
      //     assume a role and silently returns 0 assets (verified 2026-06-04).
      //     Same name, same permissions (the custom least-privilege READ list),
      //     and the SAME trust as the member StackSet role: the orchestrator
      //     ArnPrincipal gated by aws:PrincipalOrgID + a required sts:ExternalId
      //     (mirrors scanner-role-template.json's AllowOrchestratorAssumeFromOrg),
      //     so the fan-out treats every account uniformly under one trust contract.
      // ------------------------------------------------------------------
      const localScannerRole = new iam.Role(this, 'LocalScannerRole', {
        roleName: this.scannerRoleName, // 'CryptaMapScannerRole'
        // Trust EXACTLY mirrors the member StackSet template: the orchestrator
        // ArnPrincipal may assume only when aws:PrincipalOrgID == organizationId
        // AND sts:ExternalId == externalId (confused-deputy / cross-org guard).
        assumedBy: new iam.ArnPrincipal(orchestrator.roleArn).withConditions({
          StringEquals: {
            'aws:PrincipalOrgID': organizationId,
            'sts:ExternalId': externalId,
          },
        }),
        description:
          'CryptaMap read-only scanner role in the management account (counterpart to the member-account StackSet role).',
        // No managed policies: the custom least-privilege READ list (from
        // cmd/gen-policy) is attached below. READS ONLY — this role, like the
        // member StackSet role, gets NONE of the 3 orchestrator writes.
      });
      this.addScannerReadPolicy(localScannerRole);
      new cdk.CfnOutput(this, 'LocalScannerRoleArn', { value: localScannerRole.roleArn });

      // ------------------------------------------------------------------
      // 2) SERVICE_MANAGED StackSet that rolls the member scanner role out to
      //    every account under your org root. AutoDeployment=true so new accounts
      //    inherit the role; ManagedExecution.Active=true so operations run in
      //    parallel (existing IAMRollCall StackSet is serialized = false).
      //    Template body is loaded from cdk/templates/scanner-role-template.json.
      // ------------------------------------------------------------------
      const templatePath = path.join(__dirname, '..', 'templates', 'scanner-role-template.json');
      const templateBody = fs.readFileSync(templatePath, 'utf-8');

      new cdk.CfnStackSet(this, 'ScannerRoleStackSet', {
        stackSetName: 'CryptaMapScannerRole',
        description:
          'Deploys the read-only CryptaMapScannerRole to all org member accounts (your org root).',
        permissionModel: 'SERVICE_MANAGED',
        // Whether CloudFormation acts as the management-account admin (SELF) or as a
        // delegated administrator in the Audit account (DELEGATED_ADMIN, the default
        // here). DELEGATED_ADMIN assumes the operator registered the Audit account as
        // a StackSets delegated admin in the management account. Override with
        // `-c stackSetCallAs=SELF` only when deploying this stack directly from the
        // management/payer account. CallAs applies only to SERVICE_MANAGED StackSets.
        callAs: stackSetCallAs,
        autoDeployment: {
          enabled: true,
          retainStacksOnAccountRemoval: false,
        },
        managedExecution: {
          // true => operations run concurrently (not serialized).
          Active: true,
        },
        capabilities: ['CAPABILITY_NAMED_IAM'],
        operationPreferences: {
          maxConcurrentPercentage: 100,
          failureTolerancePercentage: 25,
          regionConcurrencyType: 'PARALLEL',
        },
        parameters: [
          // Full ARN of the orchestrator role in the account this stack is deployed
          // to (the Audit/delegated-admin account by default, or the management
          // account when callAs=SELF) — the only principal the member scanner role
          // will trust.
          { parameterKey: 'OrchestratorRoleArn', parameterValue: orchestrator.roleArn },
          // Org id that gates the trust policy via aws:PrincipalOrgID.
          { parameterKey: 'OrganizationId', parameterValue: organizationId },
          { parameterKey: 'ScannerRoleName', parameterValue: this.scannerRoleName },
          { parameterKey: 'ExternalId', parameterValue: externalId },
        ],
        stackInstancesGroup: [
          {
            // IAM is global; deploy the role into a single home region only.
            regions: [this.region],
            deploymentTargets: {
              organizationalUnitIds: [orgRootId],
            },
          },
        ],
        templateBody,
      });

      new cdk.CfnOutput(this, 'OrchestratorRoleArn', { value: orchestrator.roleArn });
      new cdk.CfnOutput(this, 'ScannerRoleStackSetName', { value: 'CryptaMapScannerRole' });
    }

    new cdk.CfnOutput(this, 'ScannerRoleName', { value: this.scannerRoleName });
  }

  /**
   * Attach the custom least-privilege READ policy to a scanner role. The action
   * list is the generated source of truth (scanner-actions.json, produced by
   * `cmd/gen-policy`). The policy is created once and shared across roles. This
   * REPLACES the former AWS-managed ReadOnlyAccess attachment so the scanner
   * permission surface is exactly — and only — the actions the scanner code uses.
   * READS ONLY: this method never grants any write.
   */
  private addScannerReadPolicy(role: iam.Role): void {
    if (!this.scannerReadPolicy) {
      this.scannerReadPolicy = new iam.ManagedPolicy(this, 'ScannerReadPolicy', {
        managedPolicyName: 'CryptaMapScannerReadActions',
        description:
          'CryptaMap least-privilege scanner READ actions. GENERATED from cmd/gen-policy ' +
          '(scanner-actions.json) — do not hand-edit; CI `make check-policy` fails on drift.',
        statements: [
          new iam.PolicyStatement({
            sid: 'CryptaMapScannerReads',
            effect: iam.Effect.ALLOW,
            // Read actions are account-wide List/Describe/Get verbs that do not
            // support resource-level scoping, so Resource:* matches the member
            // StackSet template. No write is ever included here.
            actions: scannerPolicy.readActions,
            resources: ['*'],
          }),
        ],
      });
    }
    role.addManagedPolicy(this.scannerReadPolicy);
  }

  /**
   * Grant the orchestrator role the EXACTLY THREE resource-scoped WRITES declared
   * in the generated contract (scanner-actions.json `orchestratorWrites`). The
   * portable placeholder tokens in each statement's resource are resolved to this
   * account's real ARNs / CloudFormation pseudo-parameters here. Member scanner
   * roles never call this — they are reads-only.
   */
  private addOrchestratorWrites(role: iam.Role, props: SecurityStackProps): void {
    // Security Hub custom-product ARN for THIS account+region (the only place the
    // orchestrator pushes findings). Matches the ASFF ProductArn the CLI stamps:
    // arn:<partition>:securityhub:<region>:<account>:product/<account>/default.
    const securityHubProductArn =
      `arn:${cdk.Aws.PARTITION}:securityhub:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:product/${cdk.Aws.ACCOUNT_ID}/default`;
    const resolve = (placeholder: string): string => {
      switch (placeholder) {
        case '{RESULTS_BUCKET_ARN}/*':
          return `${props.resultsBucket.bucketArn}/*`;
        case '{SCANS_TABLE_ARN}':
          return props.scansTable.tableArn;
        case '{SECURITYHUB_PRODUCT_ARN}':
          return securityHubProductArn;
        default:
          throw new Error(`scanner-actions.json: unknown write resource placeholder '${placeholder}'`);
      }
    };
    for (const w of scannerPolicy.orchestratorWrites) {
      role.addToPolicy(new iam.PolicyStatement({
        sid: w.sid,
        effect: iam.Effect.ALLOW,
        actions: [w.action],
        resources: [resolve(w.resource)],
      }));
    }
  }
}
