// Code generated by gen-ts; DO NOT EDIT.
//
// Single source of truth: the Go wire structs in pkg/models, internal/roadmap,
// internal/output and the enum vocabularies in pkg/models + internal/pqc.
// Regenerate with `make generate-types` (runs `go run ./cmd/gen-ts`). CI fails
// if this file is stale (regenerate + git diff --exit-code).
//
// Field names are the Go json tags verbatim; `?` optionality mirrors
// json `omitempty` / pointer / slice / map fields.

/** Canonical severity (pkg/models/finding.go Severity). */
export type Severity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'INFORMATIONAL';

/** Encryption posture (pkg/models/finding.go CryptoPosture). */
export type CryptoPosture = 'no-encryption' | 'legacy-tls' | 'non-pqc-classical' | 'symmetric-only' | 'pqc-hybrid' | 'pqc-ready' | 'unknown';

/** Asset surface category (pkg/models/asset.go Category). */
export type Category = 'data-at-rest' | 'data-in-transit' | 'certificate' | 'key-management' | 'sdk-library';

/** CycloneDX 1.7 cryptoProperties.assetType (pkg/models/asset.go AssetType). */
export type AssetType = 'algorithm' | 'certificate' | 'protocol' | 'related-crypto-material';

/** CycloneDX 1.7 algorithmProperties.primitive (pkg/models/asset.go AlgorithmPrimitive). */
export type AlgorithmPrimitive = 'ae' | 'block-cipher' | 'kem' | 'signature' | 'hash' | 'key-agree' | 'kdf' | 'mac';

/** Material lifecycle state (pkg/models/asset.go CryptoState). */
export type CryptoState = 'active' | 'suspended' | 'destroyed' | 'unknown';

/** PQC readiness status (internal/pqc/matrix.go PQCStatus). */
export type PQCStatus = 'available' | 'hybrid-tls-only' | 'not-yet' | 'not-applicable' | 'not-encrypted';

/** Effort to enable PQC (internal/pqc/matrix.go UpgradeEase). */
export type UpgradeEase = 'one-flip' | 'config-change' | 'app-change' | 'aws-managed-automatic' | 'none-available';

/** Matrix verification confidence (internal/pqc/matrix.go Confidence). */
export type Confidence = 'high' | 'medium' | 'low';

/** Symmetric-cipher strength tier (internal/pqc/primitives.go SymmetricStrength). Additive to PQCStatus. */
export type SymmetricStrength = 'quantum-safe' | 'adequate-review' | 'weak-replace' | 'likely-safe-unconfirmed';

/** ComplianceMapping.status vocabulary (pkg/models/finding.go ComplianceMapping). */
export type ComplianceStatus = 'compliant' | 'non-compliant' | 'partial' | 'informational';

/** pkg/models/finding.go MoscaScore. */
export interface MoscaScore {
  x: number;
  y: number;
  z: number;
  score: number;
  notes?: string;
}

/** pkg/models/finding.go ComplianceMapping. */
export interface ComplianceMapping {
  framework: string;
  controlId: string;
  controlName?: string;
  status: ComplianceStatus;
  remediation?: string;
  deadlineDate?: string;
}

/** pkg/models/finding.go Finding. */
export interface Finding {
  id: string;
  title: string;
  description: string;
  severity: Severity;
  posture: CryptoPosture;
  accountId: string;
  region: string;
  service: string;
  resourceId: string;
  resourceArn?: string;
  resourceType?: string;
  assetBomRef?: string;
  mosca: MoscaScore;
  compliance?: ComplianceMapping[];
  recommendation?: string;
  docsUrl?: string;
  createdAt: string;
  updatedAt: string;
}

/** pkg/models/scan.go ScanSummary. */
export interface ScanSummary {
  totalAssets: number;
  totalFindings: number;
  critical: number;
  high: number;
  medium: number;
  informational: number;
  inventoryOnly: number;
  serviceCount: number;
}

/** pkg/models/scan.go ServiceScanReport. */
export interface ServiceScanReport {
  service: string;
  assetCount: number;
  errors?: string[];
  durationMs: number;
}

/** pkg/models/scan.go ScanResult. */
export interface ScanResult {
  scanId: string;
  accountId: string;
  region: string;
  startedAt: string;
  completedAt: string;
  mode: string;
  summary: ScanSummary;
  assets: CryptoAsset[];
  findings: Finding[];
  serviceStats?: ServiceScanReport[];
  toolVersion: string;
}

/** pkg/models/scan.go MultiScanResult. */
export interface MultiScanResult {
  orchestratorAccountId: string;
  startedAt: string;
  completedAt: string;
  scans: ScanResult[];
  totalAccounts: number;
  totalRegions: number;
}

/** pkg/models/asset.go AlgorithmProperties. */
export interface AlgorithmProperties {
  primitive?: AlgorithmPrimitive;
  parameterSetIdentifier?: string;
  curve?: string;
  executionEnvironment?: string;
  implementationPlatform?: string;
  certificationLevel?: string[];
  mode?: string;
  padding?: string;
  cryptoFunctions?: string[];
  classicalSecurityLevel?: number;
  nistQuantumSecurityLevel?: number;
  keySizeBits?: number;
  kmsKeySpec?: string;
  algorithmName?: string;
}

/** pkg/models/asset.go CertificateProperties. */
export interface CertificateProperties {
  subjectName?: string;
  issuerName?: string;
  notValidBefore?: string;
  notValidAfter?: string;
  signatureAlgorithmRef?: string;
  subjectPublicKeyRef?: string;
  certificateFormat?: string;
  certificateExtension?: string;
}

/** pkg/models/asset.go CipherSuite. */
export interface CipherSuite {
  name?: string;
  algorithms?: string[];
  identifiers?: string[];
}

/** pkg/models/asset.go ProtocolProperties. */
export interface ProtocolProperties {
  type?: string;
  version?: string;
  cipherSuites?: CipherSuite[];
  ikev2TransformTypes?: string[];
  keyExchangeGroup?: string;
  pqcHybrid?: boolean;
  certSignatureAlgorithm?: string;
  certKeySizeBits?: number;
  source?: string;
  tlsMinVersion?: string;
}

/** pkg/models/asset.go RelatedCryptoMaterialProperties. */
export interface RelatedCryptoMaterialProperties {
  type?: string;
  id?: string;
  state?: CryptoState;
  algorithmRef?: string;
  creationDate?: string;
  expirationDate?: string;
  updateDate?: string;
  value?: string;
  size?: number;
  format?: string;
  securedBy?: string;
}

/** pkg/models/asset.go CryptoProperties. */
export interface CryptoProperties {
  assetType: AssetType;
  algorithmProperties?: AlgorithmProperties;
  certificateProperties?: CertificateProperties;
  protocolProperties?: ProtocolProperties;
  relatedCryptoMaterialProperties?: RelatedCryptoMaterialProperties;
  oid?: string;
}

/** pkg/models/asset.go CryptoAsset (raw discovered asset record). */
export interface CryptoAsset {
  'bom-ref': string;
  name: string;
  description?: string;
  service: string;
  category: Category;
  accountId: string;
  region: string;
  resourceId: string;
  resourceArn?: string;
  resourceType?: string;
  cryptoProperties: CryptoProperties;
  tags?: Record<string, string>;
  discoveredAt: string;
  properties?: Record<string, string>;
}

/** internal/output/cyclonedx.go CDXTool. */
export interface CDXTool {
  vendor: string;
  name: string;
  version: string;
}

/** internal/output/cyclonedx.go CDXMetaComp. */
export interface CDXMetaComp {
  type: string;
  name: string;
  'bom-ref'?: string;
}

/** internal/output/cyclonedx.go CDXProperty. */
export interface CDXProperty {
  name: string;
  value: string;
}

/** internal/output/cyclonedx.go CDXMetadata. */
export interface CDXMetadata {
  timestamp: string;
  tools: CDXTool[];
  component: CDXMetaComp;
  properties?: CDXProperty[];
}

/** internal/output/cyclonedx.go CDXComponent. */
export interface CDXComponent {
  type: string;
  'bom-ref': string;
  name: string;
  description?: string;
  cryptoProperties?: CryptoProperties;
  properties?: CDXProperty[];
}

/** internal/output/cyclonedx.go CDXBOM (top-level CycloneDX 1.7 CBOM). */
export interface CDXBOM {
  bomFormat: string;
  specVersion: string;
  serialNumber: string;
  version: number;
  metadata: CDXMetadata;
  components: CDXComponent[];
}

/** internal/roadmap/roadmap.go RoadmapItem. */
export interface RoadmapItem {
  rank: number;
  priorityScore: number;
  service: string;
  displayName: string;
  awsCategory: string;
  cryptoFunction: string;
  accountId: string;
  region: string;
  resourceId: string;
  resourceArn?: string;
  assetBomRef?: string;
  posture: CryptoPosture;
  severity: Severity;
  mosca: MoscaScore;
  hndlExposed: boolean;
  pqcStatus: PQCStatus;
  symmetricStrength?: SymmetricStrength;
  upgradeEase: UpgradeEase;
  recommendedAction: string;
  sourceUrl: string;
  confidence: Confidence;
  asOf: string;
  quickWin: boolean;
}

/** internal/roadmap/roadmap.go ServiceRollup. */
export interface ServiceRollup {
  service: string;
  displayName: string;
  items: number;
  maxPriority: number;
  sumPriority: number;
  quickWins: number;
  pqcStatus: PQCStatus;
}

/** internal/roadmap/roadmap.go AccountRollup. */
export interface AccountRollup {
  accountId: string;
  items: number;
  maxPriority: number;
  sumPriority: number;
  critical: number;
  high: number;
}

/** internal/roadmap/roadmap.go Roadmap (top-level roadmap envelope). */
export interface Roadmap {
  asOf: string;
  generatedFrom: string;
  items: RoadmapItem[];
  byService: ServiceRollup[];
  byAccount: AccountRollup[];
}

