package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/aws-samples/cryptamap/internal/pqc"
)

// knowledgeStatusFlags configure the knowledge-status subcommand.
type knowledgeStatusFlags struct {
	json bool
}

// newKnowledgeStatusCmd builds the `cryptamap knowledge-status` subcommand. It
// prints the freshness/provenance of the ACTIVE PQC knowledge — whether the
// air-gap embedded baseline or a validated newer on-disk override is in effect,
// the knowledge version + digest, the fact count, and the minAsOf "oldest fact"
// freshness headline (the conservative weakest-link date). This is the operator-
// facing half of the freshness surface (the CBOM carries the same data as
// knowledge:* metadata for downstream/air-gapped consumers).
//
// It makes NO AWS calls and no network calls: it reads the embedded knowledge
// (plus any opt-in $CRYPTAMAP_KNOWLEDGE_FILE/_DIR override) and reports. Safe to
// run in a fully air-gapped environment.
func newKnowledgeStatusCmd() *cobra.Command {
	f := knowledgeStatusFlags{}
	cmd := &cobra.Command{
		Use:   "knowledge-status",
		Short: "Show PQC knowledge freshness & provenance (source, version, oldest fact)",
		Long: `knowledge-status prints how fresh CryptaMap's post-quantum knowledge is and
where it came from:

  • source       embedded (baked-in air-gap floor) or override (a validated,
                 newer on-disk knowledge file took effect)
  • version      the knowledge version (monotonic YYYY-MM-DD)
  • oldest fact  minAsOf — the conservative "weakest-link" freshness headline:
                 the single least-recently-verified fact in the knowledge set
  • newest fact  maxAsOf
  • facts        how many dated facts the knowledge carries
  • digest       sha256 over the knowledge (tamper-/drift-evidence)

It makes NO AWS or network calls — it reports the embedded baseline (and any
opt-in $CRYPTAMAP_KNOWLEDGE_FILE / $CRYPTAMAP_KNOWLEDGE_DIR override), so it is
safe to run fully air-gapped.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runKnowledgeStatus(f)
		},
	}
	cmd.Flags().BoolVar(&f.json, "json", false, "emit the provenance as JSON (for scripts / CI)")
	return cmd
}

func runKnowledgeStatus(f knowledgeStatusFlags) error {
	prov := pqc.KnowledgeProvenanceInfo()

	if f.json {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(prov)
	}

	fmt.Println("PQC knowledge status")
	fmt.Println("====================")
	fmt.Printf("  Source:       %s\n", knowledgeSourceLabel(prov.Source))
	fmt.Printf("  Version:      %s\n", prov.KnowledgeVersion)
	fmt.Printf("  Oldest fact:  %s   (weakest-link freshness headline)\n", prov.MinAsOf)
	fmt.Printf("  Newest fact:  %s\n", prov.MaxAsOf)
	fmt.Printf("  Facts:        %d\n", prov.FactCount)
	fmt.Printf("  Digest:       %s\n", prov.Digest)
	if prov.GeneratedBy != "" {
		fmt.Printf("  Generated by: %s\n", prov.GeneratedBy)
	}
	if prov.GeneratedAt != "" {
		fmt.Printf("  Generated at: %s\n", prov.GeneratedAt)
	}
	if prov.OverridePath != "" {
		fmt.Printf("  Override:     %s\n", prov.OverridePath)
	}
	if prov.OverrideError != "" {
		// A rejected override is operationally important: the embedded floor is
		// standing because the on-disk file failed validation/precedence.
		fmt.Printf("  Override NOT applied (embedded baseline stands): %s\n", prov.OverrideError)
	}
	return nil
}

// knowledgeSourceLabel renders the active source with a human hint.
func knowledgeSourceLabel(s pqc.KnowledgeSource) string {
	switch s {
	case pqc.SourceEmbedded:
		return "embedded (baked-in air-gap baseline)"
	case pqc.SourceOverride:
		return "override (validated newer on-disk knowledge)"
	default:
		return string(s)
	}
}
