package compliance

import "github.com/aws-samples/cryptamap/pkg/models"

// MITREMapper — MITRE PQCC (Post-Quantum Cryptography Coalition).
// Provides the 18-field Inventory Workbook taxonomy. The full PQCC Excel
// export is generated by internal/output/pqcc_excel.go using these mappings.
type MITREMapper struct{}

func (m *MITREMapper) ID() string { return MITRE }

func (m *MITREMapper) Map(asset models.CryptoAsset, posture models.CryptoPosture) []models.ComplianceMapping {
	pqcNeeds := "Unknown"
	switch posture {
	case models.PostureNoEncryption, models.PostureLegacyTLS, models.PostureNonPQCClassical:
		pqcNeeds = "Needs Attention"
	case models.PosturePQCHybrid, models.PosturePQCReady, models.PostureSymmetricOnly:
		pqcNeeds = "Resolved"
	}
	return []models.ComplianceMapping{{
		Framework:   MITRE,
		ControlID:   "PQCC-INVENTORY",
		ControlName: "PQCC Inventory Workbook entry",
		Status:      pqcNeeds,
		Remediation: "Disposition recorded in PQCC Excel export (CryptaMap output).",
	}}
}
